<?php

// autoload_real.php @generated by Mozart

class MozartAutoloaderInitca064923de019edc6ab1b90a8c067942
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('MozartAutoloaderInitca064923de019edc6ab1b90a8c067942', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('MozartAutoloaderInitca064923de019edc6ab1b90a8c067942', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\MozartStaticInitca064923de019edc6ab1b90a8c067942::getInitializer($loader));

        $loader->register(true);


        return $loader;
    }
}
